Refactor result rendering.
smart-online-judge/basic-online-judge pull request #31
Opened 2020-10-30 09:15 UTC by gevorgyana

Compute the semantic and structural difference in a separate
goroutine.

[TODO] Serve the results at view/ entry point.

Closes #25 

Signed-off-by: Artyom Gevorgyan <artemhevorhian@gmail.com>

2020-10-30 09:38 UTC, Pilipets commented on web-service/upload_files.go
> +			log.Fatal(err)
I suggest using loggers here to make output to the respective files - ErrorLogger.Fatal(...).

Please change "log.Fatal(err)" several lines above as well.

2020-10-30 09:38 UTC, Pilipets commented on web-service/upload_files.go
> +	fmt.Fprint(w, "<html>%s</html>", id.String())
We won't return HTML here: the idea is to return JSON and render it as HTML if using Vue.js.
For the moment, let's return plain/text.

2020-10-30 09:38 UTC, Pilipets commented on web-service/upload_files.go
> +	go prepareViewForUUID(id)
You said there is no sense in calling goroutine here because the connection handler goes async, didn't you?
Then why using goroutine here?

2020-10-30 09:38 UTC, Pilipets commented on web-service/upload_files.go
> +	UUIDInMemCache = make(map[guuid.UUID]bool)
Maybe better to initialize it in the init(...) function - the way it's done for loggers?

2020-10-30 09:43 UTC, Pilipets commented on web-service/upload_files.go
> +	go prepareViewForUUID(id)
Ok, as discussed. We return the link here possibly without the finished calculation.

2020-10-30 10:03 UTC, gevorgyana commented on web-service/upload_files.go
> +	fmt.Fprint(w, "<html>%s</html>", id.String())
Okay clear. Will change content type to plain text.

2020-10-30 15:55 UTC, Pilipets requested changes

2020-10-30 15:55 UTC, Pilipets commented on web-service/file_upload.go
> -package main
Please, use git mv for file renaming - because modifications aren't clear without that.

2020-10-30 15:55 UTC, Pilipets commented on web-service/go.sum
> +github.com/google/uuid v1.1.2 h1:EVhdT+1Kseyi1/pUmXKaFxYsDNy9RQYkMWRH68J/W7Y=
What is it used for?

2020-10-30 16:01 UTC, Pilipets commented on web-service/file_upload.go
> -package main
Because now it's viewed as a new file - not renamed one.

2020-10-30 18:13 UTC, Pilipets requested changes

2020-10-30 18:13 UTC, Pilipets commented on web-service/file_upload.go
> +	if !err {
err is totally misleading here.
If !err you log the error - which implies err = nil. Then why printing error?
Please change either the variable name here or logic.

2020-10-30 18:13 UTC, Pilipets commented on web-service/file_upload.go
> +		if _, ok := UUIDInMemCache[id]; ok {
Maybe better name it present instead of ok? Would it provide more context?

2020-10-30 18:13 UTC, Pilipets commented on web-service/file_upload.go
> +	for {
While the probability that a UUID will be duplicated is not zero, it is close enough to zero to be negligible. Thus, anyone can create a UUID and use it to identify something with near certainty that the identifier does not duplicate one that has already been, or will be, created to identify something else.

Let's omit the loop then?

2020-10-30 18:13 UTC, Pilipets commented on web-service/file_upload.go
> +	fmt.Fprint(w, "<html>%s</html>", id.String())
Why HTML???

`fmt.Fprintf(w,"%v\n", id)`

2020-10-30 18:13 UTC, Pilipets commented on web-service/file_upload.go
> +	id, ok := guuid.Parse(id_str)
here error is the right name.
Later you check the error for the nil value - if not, log that.

2020-10-30 18:16 UTC, gevorgyana commented on web-service/file_upload.go
> +		ErrorLogger.Println(err)
Ok

2020-10-30 18:16 UTC, gevorgyana commented on web-service/file_upload.go
> +			ErrorLogger.Println(err)
Okay, something got wrong along the way and I copy-pasted it all over the code. Got you.

2020-10-30 18:17 UTC, gevorgyana commented on web-service/file_upload.go
> +	if !err {
I see.

2020-10-30 18:18 UTC, gevorgyana commented on web-service/file_upload.go
> +		if _, ok := UUIDInMemCache[id]; ok {
Okay, I thought naming it either `ok` or `err` is a convention. Expressive code is okay, though.

2020-10-30 18:18 UTC, Pilipets commented on web-service/go.sum
> +github.com/google/uuid v1.1.2 h1:EVhdT+1Kseyi1/pUmXKaFxYsDNy9RQYkMWRH68J/W7Y=
Ok, clear.

2020-10-30 18:18 UTC, gevorgyana commented on web-service/file_upload.go
> +	for {
Well, it is indeed. Do you want to avoid checking? I don't know...

2020-10-30 18:19 UTC, gevorgyana commented on web-service/file_upload.go
> +	fmt.Fprint(w, "<html>%s</html>", id.String())
My bad.

2020-10-30 18:19 UTC, gevorgyana commented on web-service/file_upload.go
> +	id, ok := guuid.Parse(id_str)
Okay.

2020-10-30 18:21 UTC, gevorgyana commented on web-service/file_upload.go
> +	for {
Does this piece of advice come from experts?

2020-10-30 18:24 UTC, Pilipets commented on web-service/file_upload.go
> +	UUIDIsReadyForView map[guuid.UUID]bool
I don't really understand why not to use struct already?

We will simply store the map with the computed results.
If requesting a view for the key that's in the map, just return "Result not present" in the response.
Won't it simplify the whole logic?

`type ComputeResult struct {
	uuid guuid.UUID
	similarity_mat [][]float32
}
`

2020-10-30 18:28 UTC, Pilipets commented on web-service/file_upload.go
> +	for {
https://towardsdatascience.com/are-uuids-really-unique-57eb80fc2a87
Exactly

2020-10-30 18:28 UTC, Pilipets commented on web-service/file_upload.go
> +	for {
Check the probability of uniqueness here.

2020-10-31 16:09 UTC, gevorgyana commented on web-service/file_upload.go
> +		if _, ok := UUIDInMemCache[id]; ok {
No, I see ok all over the place. It is okay. In Rust, they have an explicit enum for that, I think in Go, the authors did not care to create a enum for that, but they wanted to have the same name too. That is why there are plently of examples on the Internet doing the same - naming errors `err` and boolean values `ok`.

2020-10-31 16:10 UTC, gevorgyana commented on web-service/file_upload.go
> +	for {
No, I am talking about engineering experts, not mathematicians.

2020-10-31 16:12 UTC, gevorgyana commented on web-service/file_upload.go
> +	for {
I do not really care about math - I am just interested in making a secure and resilient system. If we can spend little memory and time for that, then that is what we should do.

2020-10-31 16:29 UTC, gevorgyana commented on web-service/file_upload.go
> +	UUIDIsReadyForView map[guuid.UUID]bool
It is coming in another PR.

2020-10-31 16:29 UTC, gevorgyana commented on web-service/file_upload.go
> +	UUIDIsReadyForView map[guuid.UUID]bool
The struct is another PR. 

I will refactor the use of maps now.

2020-10-31 16:31 UTC, gevorgyana commented on web-service/file_upload.go
> +	UUIDIsReadyForView map[guuid.UUID]bool
It doesn't really make sense to do this here, as the other PR fixes it.

2020-10-31 17:52 UTC, gevorgyana commented on web-service/file_upload.go
> +	UUIDIsReadyForView map[guuid.UUID]bool
Will do it.

2020-10-31 20:14 UTC, gevorgyana commented on web-service/file_upload.go
> +	UUIDIsReadyForView map[guuid.UUID]bool
Removed excessive memory allocation and stopped handling concurrency issues because of their low likelihood.

2020-10-31 20:59 UTC, Pilipets requested changes

2020-10-31 20:59 UTC, Pilipets commented on web-service/file_upload.go
> +		fmt.Printf("Result for %s is not yet ready", id);
Print this to the response

2020-10-31 20:59 UTC, Pilipets commented on web-service/file_upload.go
> +	// Report a link to the personal room
As you are writing so many comments, please, write them correctly. 

Change to something like triggering similarity computations and generating a link to the personal room.
Or move this comment to the actual link printing logic - not UUID generation.

2020-10-31 20:59 UTC, Pilipets commented on web-service/file_upload.go
> +	// Report a link to the personal room
But that's a suggestion.

2020-10-31 20:59 UTC, Pilipets commented on web-service/file_upload.go
Change the size of the files to be about 5Mb.

2020-10-31 20:59 UTC, Pilipets commented on web-service/file_upload.go
> +		err := os.Mkdir("uploaded", 0777)
Did you check the default file permission value - it's 777...
No need for that, though not critical.

2020-10-31 20:59 UTC, Pilipets commented on web-service/file_upload.go
> +	// TODO Make sure "NLP" is seen here.
// TODO Make sure "NLP" is seen here.
 // See how guuid is imported

Is enough, clear :)

2020-10-31 21:03 UTC, gevorgyana commented on web-service/file_upload.go
> +		err := os.Mkdir("uploaded", 0777)
Okay, interesting to find out.

2020-10-31 21:23 UTC, Pilipets approved these changes

2020-10-31 21:40 UTC, merged