Implement a daemon to be run periodically
smart-online-judge/basic-online-judge pull request #32
Opened 2020-10-31 17:48 UTC by gevorgyana

- Meant to be run once in 5 minutes to clean user files.
- Introduces meta.json to contain timestamps.
Closes #27 
Signed-off-by: Artyom Gevorgyan <artemhevorhian@gmail.com>

2020-10-31 22:31 UTC, Pilipets requested changes
To sum up, the logic can be simplified a lot here.

Why using JSON at all?
os.Open("meta.json")

We will either use a database and select the rows with the expired timestamp or runtime memory - don't see the need for additional meta.json.
Correct me if I'm wrong

2020-10-31 22:31 UTC, Pilipets commented on web-service/daemon.go
> +func clean() {
Ok, considering your comment "This should be run once in every 5 minutes.", the logic is wrong.
What happens if the `clean(...)` doesn't finish its work in five minutes???
No, it mustn't be called again.

Normally, you will have the loop which runs this function with 5 minutes idle at the end of execution.
So correct the comment.

2020-10-31 22:31 UTC, Pilipets commented on web-service/daemon.go
> +	// if `root` does not exist, then exit
The logic is self-explanatory here - no need for the comment.

2020-10-31 22:31 UTC, Pilipets commented on web-service/daemon.go
> +			if storedCalculation.TimeStamp.Unix() < time.Now().Unix() {
Call this function once and store the result - that will make more sense.

2020-10-31 22:31 UTC, Pilipets commented on web-service/daemon.go
> +// This struct uses struct tags, google it if you don't know
This looks weird - why not using the array without struct????

2020-10-31 22:31 UTC, Pilipets commented on web-service/daemon.go
> +		log.Fatal(err)
Why not logging into the respective error logger? How will you trace this output when running remotely?

2020-10-31 22:32 UTC, Pilipets commented on web-service/daemon.go
> +		log.Fatal(err)
Please, use the logger name the same as the package name or, at least, derived from it.

2020-11-01 00:09 UTC, gevorgyana commented
> To sum up, the logic can be simplified a lot here.
> 
> Why using JSON at all?
> os.Open("meta.json")
> 
> We will either use a database and select the rows with the expired timestamp or runtime memory - don't see the need for additional meta.json.
> Correct me if I'm wrong

Let's use a database.

2020-11-01 00:16 UTC, gevorgyana commented on web-service/daemon.go
> +// This struct uses struct tags, google it if you don't know
hen using JSON support in golang, we should map a sequence of values (JSON array) into a corresponding structure in Go. Does this answer the question?

2020-11-29 00:49 UTC, gevorgyana commented
Needs a serious update.

Here https://github.com/smart-online-judge/basic-online-judge/issues/40 it is discussed that we store files locally and for computations, then remove the files and push them to the object storage for future retrieval.

So we need to clean only the data from the object storage.

2020-12-10 11:31 UTC, gevorgyana commented
Closed in favour of #86

2020-12-10 11:31 UTC, closed without merging