I40
smart-online-judge/basic-online-judge pull request #68
Opened 2020-11-27 16:30 UTC by gevorgyana

closes #40
resolves #40
fixes #40

2020-11-27 16:31 UTC, gevorgyana commented
shit. rebasing is required..........

2020-11-27 17:40 UTC, gevorgyana commented
too crazy to resolve this.

2020-11-27 19:32 UTC, Pilipets commented on web-service/s3support/wrap_minio.go
> +func StoreFileByUUID(id guuid.UUID, file io.Reader, fileName string) {
Have you checked the original variable format that is passed here - it's `multipart.File`. Is it done intentionally?

2020-11-27 19:40 UTC, Pilipets requested changes
Please, clear this code from extra comments, use go tidy and go fmt.

The example of file uploading can be taken from here - https://docs.min.io/docs/golang-client-quickstart-guide.html, so no need for a lot of comments.

In the future, we should run the "minio" in the embedded way like proposed here - https://github.com/minio/minio/issues/5146.

2020-11-27 19:40 UTC, Pilipets commented on web-service/s3support/wrap_minio.go
> +	_, err := minioClient.PutObject(context.Background(), bucketName, objectName, file, -1, minio.PutObjectOptions{ContentType: "application/octet-stream"})
Actually, "By default, the content type is set to application/octet-stream", but are you sure we need a binary file here?

2020-11-27 19:40 UTC, Pilipets commented on web-service/src/api/controllers/upload_files_controller.go
> +		s3support.StoreFileByUUID(id, infile, fh.Filename)
Can't we upload all these files at once on the "minio" - what is the reason for iterating over them???

2020-11-27 20:22 UTC, Pilipets commented
One more thing - since the "minio" server is external, how could we know when the files were uploaded there?
Because in the provided scenario out service calls the python which should request that data from the "minio", but it can simply fail because the files weren't uploaded yet.

2020-11-27 22:25 UTC, gevorgyana commented on web-service/s3support/wrap_minio.go
> +func StoreFileByUUID(id guuid.UUID, file io.Reader, fileName string) {
What? I suggest reading on how to work with interfaces in Go.

2020-11-27 22:26 UTC, gevorgyana commented on web-service/s3support/wrap_minio.go
> +	_, err := minioClient.PutObject(context.Background(), bucketName, objectName, file, -1, minio.PutObjectOptions{ContentType: "application/octet-stream"})
These variables are here for clarity. Remove them -- and questions will arise.

2020-11-27 22:27 UTC, gevorgyana commented on web-service/src/api/controllers/upload_files_controller.go
> +		s3support.StoreFileByUUID(id, infile, fh.Filename)
No, never seen anything like that. It does not make sense, to me.

2020-11-27 22:29 UTC, gevorgyana commented
> One more thing - since the "minio" server is external, how could we know when the files were uploaded there?

We have Python/Go SDK for that. We know the UUIDs, we can check if a file with such a uuid in name exists.

> Because in the provided scenario our service calls the python, which should request that data from the "minio", but can simply fail because the files weren't uploaded yet.

2020-11-28 00:15 UTC, gevorgyana commented on web-service/src/api/controllers/upload_files_controller.go
> +		s3support.StoreFileByUUID(id, infile, fh.Filename)
It makes sense but there is no api for that.

2020-11-28 00:18 UTC, Pilipets commented on web-service/s3support/wrap_minio.go
> +	_, err := minioClient.PutObject(context.Background(), bucketName, objectName, file, -1, minio.PutObjectOptions{ContentType: "application/octet-stream"})
I won't have any questions.

2020-11-28 08:30 UTC, gevorgyana commented
`A Context is safe for simultaneous use by multiple goroutines. Code can pass a single Context to any number of goroutines and cancel that Context to signal all of them.`

So it is beneficial to have distributed Contexts.

2020-11-28 08:55 UTC, gevorgyana commented
As of now, the logging package is not designed to be shared among  the packages
Expected: just import package and be ready to use it
How it might  work: inside `init` in logging initialize the variables by directing them to files and setting the prefix.

2020-11-28 09:25 UTC, gevorgyana commented
Updated the Logging logic, also for simplicity we should have `CreateFileIfNotExists` function that does what its name suggests. So that we can read easily.

2020-11-28 12:05 UTC, gevorgyana commented
As disucussed, the plain now is to:

- Upload files to temporary directory (upload), thus preserving the Python logic and not loading the memory with a lot of potentially big files. We will remove these files when `GetPairswiseSimilarity` ends.

2020-11-28 14:19 UTC, gevorgyana commented
Major changes, as discussed.

We will store files locally as we previously did. Then upload them to the minIO and remove from the local storage.

2020-11-28 23:48 UTC, Pilipets commented on web-service/src/api/controllers/upload_files_controller.go
> +		s3support.StoreFileByUUID(id, infile, fh.Filename)
Agree, ok.

2020-11-29 01:22 UTC, Pilipets requested changes
Good with some moments left uncovered.

2020-11-29 01:22 UTC, Pilipets commented on web-service/src/api/controllers/view_room_controller.go
> +	if /*err != nil*/ false {
Why is it commented?

2020-11-29 01:22 UTC, Pilipets commented on web-service/src/api/controllers/view_room_controller.go
> +	os.Remove(path.Join(config.UploadFilesDir, id.String()))
From the https://golang.org/pkg/os/#Remove, Remove removes the named file or (empty) directory. If there is an error, it will be of type *PathError.

If for any reason python calculation fails, we won't start uploading the files on the "minio", thus this will fail.

Check the RemoveAll method with the purpose of removing all files.

2020-11-29 01:22 UTC, Pilipets commented on web-service/src/api/controllers/view_room_controller.go
> +			err = s3support.StoreFileByUUID(id, file_, file.Name())
Please, add a comment here about error treatment when uploading on Minio.
And we can simple use FputObject to avoid opening/closing errors here.

2020-11-29 01:22 UTC, Pilipets commented on web-service/src/config/config.go
> +package config
Nice idea, but as suggested, move more constants from the project here.

2020-11-29 01:22 UTC, Pilipets commented on web-service/main.go
> -	api.InitializeUploadFilesController(UploadFilesDir)
I would suggest still creating the parent folder here, why not?

2020-11-29 01:22 UTC, Pilipets commented on web-service/s3support/wrap_minio.go
> +	// - "-1" means "unknown size"
`context.Background()` - we already have the rootCtx in the variable, let's pass it here then.

2020-11-29 01:22 UTC, Pilipets commented on web-service/s3support/wrap_minio.go
> +	_, err := minioClient.PutObject(context.Background(), bucketName, objectName, file, -1, minio.PutObjectOptions{ContentType: "application/octet-stream"})
While I agree, this information isn't used, I still suggest we provide meaningful metadata in the PutObjectOptions.

`ContentType:` "application/text"
`ContentEncoding`:  "utf-8"

Let me know if you don't see sense in it.

2020-11-29 01:26 UTC, Pilipets commented
Conflicting files
web-service/go.sum
web-service/src/api/controllers/view_room_controller.go

Please, resolve these conflicts as well.

2020-11-29 07:19 UTC, gevorgyana commented on web-service/s3support/wrap_minio.go
> +	_, err := minioClient.PutObject(context.Background(), bucketName, objectName, file, -1, minio.PutObjectOptions{ContentType: "application/octet-stream"})
Will test it.

2020-11-29 07:20 UTC, gevorgyana commented on web-service/main.go
> -	api.InitializeUploadFilesController(UploadFilesDir)
I want to decouple logic into separate packages.

2020-11-29 07:20 UTC, gevorgyana commented on web-service/src/config/config.go
> +package config
Okay

2020-11-29 07:23 UTC, gevorgyana commented on web-service/src/api/controllers/upload_files_controller.go
> +	os.MkdirAll(path.Join(config.UploadFilesDir, id.String()), os.ModePerm)
It is parent to a user request, which is not available at initialization time

2020-11-30 18:09 UTC, Pilipets commented on web-service/src/api/controllers/upload_files_controller.go
> +	os.MkdirAll(path.Join(config.UploadFilesDir, id.String()), os.ModePerm)
What do you mean by not available? We can create a parent directory - `config.UploadFilesDir` - at the initialization stage.

2020-11-30 18:12 UTC, Pilipets commented on web-service/main.go
> -	api.InitializeUploadFilesController(UploadFilesDir)
Ok, that's a good point.
In that case, we should create the init() method in the api package, which obtains the respective logger and creates the parent directory using config.

2020-12-02 10:45 UTC, gevorgyana commented on web-service/s3support/wrap_minio.go
> +	_, err := minioClient.PutObject(context.Background(), bucketName, objectName, file, -1, minio.PutObjectOptions{ContentType: "application/octet-stream"})
done, it is just metadata, i see now. it does not have influence on the actual raw binary data.

2020-12-02 10:49 UTC, gevorgyana commented on web-service/s3support/wrap_minio.go
> +	// - "-1" means "unknown size"
outdated?

2020-12-02 10:50 UTC, gevorgyana commented on web-service/src/config/config.go
> +package config
let's add them as needed.

2020-12-02 10:50 UTC, gevorgyana commented on web-service/src/api/controllers/view_room_controller.go
> +			err = s3support.StoreFileByUUID(id, file_, file.Name())
let's have a more versatile api.

2020-12-02 11:46 UTC, Pilipets commented on web-service/s3support/wrap_minio.go
> +	// - "-1" means "unknown size"
No

2020-12-02 13:45 UTC, Pilipets commented on web-service/s3support/wrap_minio.go
> +	loggingPath = "wrapMinIO.log"
Where is this logging file gonna be created?

We have the respective logging directory for that.

2020-12-02 14:20 UTC, Pilipets commented on web-service/s3support/wrap_minio.go
> +	// - "-1" means "unknown size"
The better option is passing the context as a parameter to the file upload function since it allows one to cancel/wait on the task's execution when running from separate goroutines.

2020-12-02 14:45 UTC, Pilipets approved these changes

2020-12-02 14:46 UTC, merged