Create api endpoint for serving files
smart-online-judge/basic-online-judge pull request #76
Opened 2020-12-03 23:49 UTC by gevorgyana

- Users of `link/` endpoint are now able to download files from
the bucket with a 1-hr valid download link.

closes #58 

Signed-off-by: Artyom Gevorgyan <artemhevorhian@gmail.com>

2020-12-03 23:59 UTC, gevorgyana commented on web-service/src/api/controllers/link_controller.go
> +	w.Header().Add("Content-Type", "application/json")
should be Set()

2020-12-03 23:59 UTC, gevorgyana commented on web-service/src/api/controllers/link_controller.go
> +*/
Don't need this

2020-12-03 23:59 UTC, gevorgyana commented on web-service/src/s3support/wrap_minio.go
> +	presignedURL, err := minioClient.PresignedGetObject(rootCtx, bucketName, path.Join(id.String(), fileName), time.Second*24*60*60, reqParams)
No need for this much. 1 hr is okay as the comment says. Forgot to update, probably.

2020-12-04 00:00 UTC, Pilipets requested changes

2020-12-04 00:01 UTC, gevorgyana commented on web-service/src/api/controllers/link_controller.go
> +	w.Write([]byte(jsonEncoded))
Write accepts bytes, not strings

2020-12-04 00:02 UTC, gevorgyana commented on web-service/src/api/controllers/link_controller.go
> +func ServeFileViewByUUID(w http.ResponseWriter, req *http.Request) {
Will decline any type of requests except GET.
GetFileLinkById will use it, sir.

2020-12-04 00:02 UTC, gevorgyana commented on web-service/src/s3support/wrap_minio.go
> +	fmt.Println(fileNames)
ok

2020-12-04 00:02 UTC, gevorgyana commented on web-service/src/s3support/wrap_minio.go
> +	presignedURL, err := minioClient.PresignedGetObject(rootCtx, bucketName, path.Join(id.String(), fileName), time.Second*24*60*60, reqParams)
Must? It is really a dummy variable. It has no meaning for us, agree? We control the expiration time using the database.

2020-12-04 00:04 UTC, gevorgyana commented on web-service/src/api/controllers/link_controller.go
> +		errorLogger.Println(err)
will remove this.

2020-12-04 00:04 UTC, gevorgyana commented on web-service/src/api/controllers/link_controller.go
> +		errorLogger.Println(err)
will remove this

2020-12-04 00:04 UTC, gevorgyana commented on web-service/src/s3support/wrap_minio.go
> +		Recursive: true,
it is necessary for correctness.

2020-12-04 00:08 UTC, Pilipets commented on web-service/src/s3support/wrap_minio.go
> +	presignedURL, err := minioClient.PresignedGetObject(rootCtx, bucketName, path.Join(id.String(), fileName), time.Second*24*60*60, reqParams)
I would assign it to ten minutes then.

2020-12-04 00:39 UTC, Pilipets approved these changes

2020-12-04 00:43 UTC, merged