I85
smart-online-judge/basic-online-judge pull request #87
Opened 2020-12-10 09:24 UTC by gevorgyana

Working yet.

2020-12-10 12:43 UTC, gevorgyana reviewed
A small comment on unit tests. Just read this

А как юнит тесты лучше организовать? В Расте пишту в подмодуле каждого модуля. В гоу тоже так принято? Ну тут подмодулей не будет, но я имею в виду как-то так организовать тесты

package.go
test/package_test.go

И так для каждого модуля.

---

package.go и package_test.go спокойно живут в одной папке, но у _test имя пакета может отличаться от основного

2020-12-10 12:43 UTC, gevorgyana commented on web-service/main.go
> -
We can't have this thing in the main package, as we should import the initialization logic in unit tests (means linear complexity - for each unit!), and we can't import main package.

2020-12-10 12:43 UTC, gevorgyana commented on web-service/main.go
> +	utils.ErrorLogger.Fatalln(http.ListenAndServe(config.Server.Port, nil))
It was really excessive to have vars declared in this module. They were referring to `utils`-loggers anyway.

2020-12-14 01:59 UTC, gevorgyana commented
closes #69 and #85

2020-12-14 09:37 UTC, Pilipets requested changes

2020-12-14 09:37 UTC, Pilipets commented on web-service/src/server/server.go
> +	conf *config.Configuration) *Server {
Why is this in the production code?
It shouldn't be there: we can ignore the building of testing files for the release build, but this method interferes with that idea.

2020-12-14 09:37 UTC, Pilipets commented on web-service/src/config/config.go
> +)
What for?

2020-12-14 09:37 UTC, Pilipets commented on web-service/src/s3support/fuzz_test.go
> +func TestFuzz(t *testing.T) {
Please, write a meaningful name for the test, so one won't strive to guess what it does.

2020-12-14 09:37 UTC, Pilipets commented on web-service/src/server/api_test.go
> +func UploadFilesActivityWorksInNormalUseCase(t *testing.T) {
This looks like the test with one file only, so designate it somehow in the method name.

2020-12-14 13:33 UTC, gevorgyana commented on web-service/src/server/server.go
> +	conf *config.Configuration) *Server {
I want a suggestion then. How do we test the handlers in isolation? We can't access them without creating an instance of this type.

2020-12-14 13:43 UTC, gevorgyana commented on web-service/src/server/api_test.go
> +func UploadFilesActivityWorksInNormalUseCase(t *testing.T) {
The name is `$TESTED_FUNCTION_NAME + SomeDescriptiveLogicForDeveloper`.

2020-12-19 14:46 UTC, Pilipets submitted a review, later dismissed
Good start for testing.

2020-12-19 14:47 UTC, Pilipets commented
Please, don't forget to squash two commits into one when merging.

2020-12-20 12:16 UTC, Pilipets commented on web-service/src/server/server.go
> +	conf *config.Configuration) *Server {
We don't need this method at all - it just passes nil dependencies.
You can use `func NewServer(...)` for that purpose.

2020-12-20 18:11 UTC, Pilipets commented
Remove `func NewTestServer(...)` and use `func NewServer(...)` with the respective parameters instead.

2020-12-20 21:59 UTC, Pilipets approved these changes

2020-12-20 22:01 UTC, merged